use super::*;
use serde_json::json;

#[test]
fn extracts_video_ids_from_common_urls() {
    assert_eq!(
        video_id_from_url("https://www.youtube.com/watch?v=dQw4w9WgXcQ").unwrap(),
        "dQw4w9WgXcQ"
    );
    assert_eq!(
        video_id_from_url("https://youtu.be/dQw4w9WgXcQ?si=x").unwrap(),
        "dQw4w9WgXcQ"
    );
    assert_eq!(
        video_id_from_url("https://www.youtube.com/shorts/dQw4w9WgXcQ").unwrap(),
        "dQw4w9WgXcQ"
    );
    assert_eq!(video_id_from_url("dQw4w9WgXcQ").unwrap(), "dQw4w9WgXcQ");
}

#[test]
fn rejects_non_youtube_urls() {
    assert!(video_id_from_url("https://example.com/watch?v=dQw4w9WgXcQ").is_err());
}

#[test]
fn extracts_player_response_json_from_html() {
    let html = r#"<script>var ytInitialPlayerResponse = {"videoDetails":{"title":"Hi \"there\""}};</script>"#;
    let player = player_response_from_html(html).unwrap();
    assert_eq!(player["videoDetails"]["title"], "Hi \"there\"");
}

#[test]
fn returns_manual_and_auto_tracks() {
    let player = json!({
        "captions": {
            "playerCaptionsTracklistRenderer": {
                "captionTracks": [
                    {
                        "baseUrl": "https://www.youtube.com/api/timedtext?a=1",
                        "languageCode": "en",
                        "name": { "simpleText": "English" }
                    },
                    {
                        "baseUrl": "https://www.youtube.com/api/timedtext?a=2",
                        "languageCode": "de",
                        "kind": "asr",
                        "name": { "runs": [{ "text": "German" }] }
                    }
                ]
            }
        }
    });
    let tracks = page_tracks(&player)
        .iter()
        .enumerate()
        .map(|(index, track)| track_json(index, track))
        .collect::<Vec<_>>();
    assert_eq!(tracks.len(), 2);
    assert_eq!(tracks[0]["label"], "English");
    assert_eq!(tracks[0]["isAutoGenerated"], false);
    assert_eq!(tracks[1]["label"], "German");
    assert_eq!(tracks[1]["isAutoGenerated"], true);
}

#[test]
fn caption_body_to_text_parses_vtt_and_xml() {
    let vtt = "WEBVTT\n\n00:00:01.000 --> 00:00:02.000\nHello <i>world</i>\n";
    assert_eq!(caption_body_to_text(vtt).unwrap(), "Hello world");

    let xml = r#"<transcript><text start="1" dur="2">Tom &amp; Jerry</text><text start="3" dur="2">Hi</text></transcript>"#;
    assert_eq!(caption_body_to_text(xml).unwrap(), "Tom & Jerry\nHi");
}

#[test]
fn format_caption_url_replaces_existing_format() {
    let url = format_caption_url("https://www.youtube.com/api/timedtext?v=x&fmt=json3&lang=en");
    assert!(url.contains("fmt=vtt"));
    assert!(!url.contains("fmt=json3"));
}

#[test]
fn ytdlp_track_language_prefers_language_code_and_falls_back_to_vssid() {
    let track = json!({ "languageCode": "en", "vssId": "a.de" });
    assert_eq!(ytdlp_track_language(&track).as_deref(), Some("en"));

    let track = json!({ "vssId": ".pl" });
    assert_eq!(ytdlp_track_language(&track).as_deref(), Some("pl"));
}

#[test]
fn find_subtitle_file_finds_ytdlp_vtt_output() {
    let temp = tempfile::tempdir().unwrap();
    let path = temp.path().join("video.en.vtt");
    std::fs::write(&path, "WEBVTT\n\n00:00:01.000 --> 00:00:02.000\nHi\n").unwrap();
    assert_eq!(find_subtitle_file(temp.path()).unwrap(), Some(path));
}

#[test]
fn host_ytdlp_invocations_run_the_script_through_host_python() {
    use std::collections::HashMap;

    let invocations = host_ytdlp_invocations(Path::new("/run/host"));
    assert_eq!(invocations.len(), 2);

    let wrapped = &invocations[0];
    assert_eq!(
        wrapped.program,
        Path::new("/run/host")
            .join("usr")
            .join("bin")
            .join("python3")
            .into_os_string()
    );
    assert_eq!(
        wrapped.prefix_args,
        vec![
            Path::new("/run/host")
                .join("usr")
                .join("bin")
                .join("yt-dlp")
                .into_os_string()
        ]
    );
    let env: HashMap<_, _> = wrapped
        .env
        .iter()
        .map(|(key, value)| {
            (
                key.to_string_lossy().into_owned(),
                value.to_string_lossy().into_owned(),
            )
        })
        .collect();
    assert!(
        env["PYTHONPATH"]
            .replace('\\', "/")
            .starts_with("/run/host/usr/lib/python3/dist-packages"),
        "PYTHONPATH was {}",
        env["PYTHONPATH"]
    );
    assert!(
        env["LD_LIBRARY_PATH"]
            .replace('\\', "/")
            .contains("/run/host/usr/lib/x86_64-linux-gnu"),
        "LD_LIBRARY_PATH was {}",
        env["LD_LIBRARY_PATH"]
    );

    let bare = &invocations[1];
    assert_eq!(
        bare.program,
        Path::new("/run/host")
            .join("usr")
            .join("bin")
            .join("yt-dlp")
            .into_os_string()
    );
    assert!(bare.prefix_args.is_empty());
    assert!(bare.env.is_empty());
}

#[test]
fn host_ytdlp_invocations_support_the_snap_hostfs_prefix() {
    use std::collections::HashMap;

    let invocations = host_ytdlp_invocations(Path::new("/var/lib/snapd/hostfs"));
    let wrapped = &invocations[0];
    assert_eq!(
        wrapped.program,
        Path::new("/var/lib/snapd/hostfs")
            .join("usr")
            .join("bin")
            .join("python3")
            .into_os_string()
    );
    let env: HashMap<_, _> = wrapped
        .env
        .iter()
        .map(|(key, value)| {
            (
                key.to_string_lossy().into_owned(),
                value.to_string_lossy().into_owned(),
            )
        })
        .collect();
    assert!(
        env["PYTHONPATH"]
            .replace('\\', "/")
            .starts_with("/var/lib/snapd/hostfs/usr/lib/python3/dist-packages"),
        "PYTHONPATH was {}",
        env["PYTHONPATH"]
    );
    assert!(
        env["LD_LIBRARY_PATH"]
            .replace('\\', "/")
            .contains("/var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu"),
        "LD_LIBRARY_PATH was {}",
        env["LD_LIBRARY_PATH"]
    );
}

#[test]
fn ytdlp_commands_dedupe_keeps_wrapped_and_bare_host_candidates() {
    let wrapped = YtdlpInvocation {
        program: OsString::from("/run/host/usr/bin/python3"),
        prefix_args: vec![OsString::from("/run/host/usr/bin/yt-dlp")],
        env: Vec::new(),
    };
    let bare = YtdlpInvocation {
        program: OsString::from("/run/host/usr/bin/yt-dlp"),
        prefix_args: Vec::new(),
        env: Vec::new(),
    };
    let deduped = dedupe_invocations(vec![
        plain_ytdlp(OsString::from("yt-dlp")),
        wrapped.clone(),
        bare.clone(),
        plain_ytdlp(OsString::from("yt-dlp")),
    ]);
    assert_eq!(deduped.len(), 3);
    assert!(deduped.iter().any(|item| item.program == wrapped.program));
    assert!(deduped.iter().any(|item| item.program == bare.program));
}

#[cfg(unix)]
#[test]
fn ytdlp_failures_report_what_ytdlp_said() {
    use std::os::unix::fs::PermissionsExt;

    let dir = tempfile::tempdir().unwrap();
    let script = dir.path().join("yt-dlp");
    std::fs::write(
        &script,
        "#!/bin/sh\necho 'ERROR: [youtube] abc: Sign in to confirm you are not a bot' >&2\nexit 1\n",
    )
    .unwrap();
    std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755)).unwrap();
    let info = VideoInfo {
        id: "abcdefghijk".to_string(),
        title: String::new(),
        author: String::new(),
        thumbnail_url: String::new(),
        player: json!({}),
    };

    let error = run_ytdlp(
        &plain_ytdlp(script.into_os_string()),
        &info,
        &json!({}),
        "de",
        Instant::now() + Duration::from_secs(30),
    )
    .unwrap_err()
    .to_string();
    assert!(
        error.contains("Sign in to confirm you are not a bot"),
        "{error}"
    );
}

#[cfg(unix)]
#[test]
fn ytdlp_stops_at_the_shared_deadline_and_missing_candidates_are_told_apart() {
    use std::os::unix::fs::PermissionsExt;

    let dir = tempfile::tempdir().unwrap();
    let script = dir.path().join("yt-dlp");
    std::fs::write(
        &script,
        "#!/bin/sh
sleep 5
",
    )
    .unwrap();
    std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755)).unwrap();
    let started = Instant::now();
    let error = run_ytdlp_process(
        &plain_ytdlp(script.into_os_string()),
        &[],
        Instant::now() + Duration::from_millis(300),
    )
    .unwrap_err();
    assert!(matches!(error, YtdlpError::TimedOut), "{error}");
    assert!(started.elapsed() < Duration::from_secs(3));

    let missing = run_ytdlp_process(
        &plain_ytdlp(dir.path().join("not-installed").into_os_string()),
        &[],
        Instant::now() + Duration::from_secs(5),
    )
    .unwrap_err();
    assert!(matches!(missing, YtdlpError::Missing(_)), "{missing}");
}

#[test]
fn ytdlp_video_json_lists_manual_then_original_automatic_tracks() {
    let json = json!({
        "title": "Ein Video",
        "uploader": "Kanal",
        "thumbnail": "https://i.ytimg.com/vi/abc/maxres.jpg",
        "subtitles": {
            "fr": [{ "ext": "vtt", "name": "French" }],
            "de": [{ "ext": "vtt", "name": "German" }],
            "live_chat": [{ "ext": "json", "url": "https://www.youtube.com/watch?v=abc" }]
        },
        // yt-dlp lists the automatic track as "de" and "de-orig", and one
        // machine translation per language, fetched with `tlang`.
        "automatic_captions": {
            "de": [{ "ext": "vtt", "name": "German (auto)", "url": "https://www.youtube.com/api/timedtext?v=abc&lang=de&kind=asr&fmt=vtt" }],
            "de-orig": [{ "ext": "vtt", "name": "German (Original)", "url": "https://www.youtube.com/api/timedtext?v=abc&lang=de&kind=asr&fmt=vtt" }],
            "en": [{ "ext": "vtt", "name": "English", "url": "https://www.youtube.com/api/timedtext?v=abc&lang=de&kind=asr&fmt=vtt&tlang=en" }],
            "pl": [{ "ext": "vtt", "name": "Polish", "url": "https://www.youtube.com/api/timedtext?v=abc&lang=de&kind=asr&fmt=vtt&tlang=pl" }]
        }
    });
    let (info, tracks) = tracks_from_ytdlp_json("abcdefghijk", &json);
    assert_eq!(info.title, "Ein Video");
    assert_eq!(info.author, "Kanal");
    assert_eq!(info.thumbnail_url, "https://i.ytimg.com/vi/abc/maxres.jpg");
    let listed = tracks
        .iter()
        .enumerate()
        .map(|(index, track)| track_json(index, track))
        .collect::<Vec<_>>();
    assert_eq!(listed.len(), 3);
    assert_eq!(listed[0]["languageCode"], "de");
    assert_eq!(listed[0]["isAutoGenerated"], false);
    assert_eq!(listed[1]["languageCode"], "fr");
    assert_eq!(listed[2]["label"], "German (auto)");
    assert_eq!(listed[2]["isAutoGenerated"], true);
    // yt-dlp downloads these tracks by language and kind.
    assert!(track_is_auto_generated(&tracks[2]));
    assert_eq!(ytdlp_track_language(&tracks[2]).as_deref(), Some("de"));
}

#[test]
fn a_download_takes_the_picked_track_when_the_list_order_changed() {
    let page_order = [
        json!({ "languageCode": "en", "kind": "manual" }),
        json!({ "languageCode": "en", "kind": "asr" }),
    ];
    let ytdlp_order = [
        json!({ "languageCode": "en", "kind": "manual" }),
        json!({ "languageCode": "af", "kind": "asr" }),
        json!({ "languageCode": "en", "kind": "asr" }),
    ];
    let picked = pick_track(&ytdlp_order, 1, Some(("en", true))).unwrap();
    assert_eq!(picked.0, 2);
    assert_eq!(pick_track(&page_order, 1, Some(("en", true))).unwrap().0, 1);
    assert!(pick_track(&page_order, 1, Some(("de", true))).is_none());
    // Older frontends send only the index.
    assert_eq!(pick_track(&ytdlp_order, 1, None).unwrap().0, 1);
}
