use super::*;
use serde_json::json;

#[test]
fn extracts_video_ids_from_common_urls() {
    assert_eq!(
        video_id_from_url("https://www.youtube.com/watch?v=dQw4w9WgXcQ").unwrap(),
        "dQw4w9WgXcQ"
    );
    assert_eq!(
        video_id_from_url("https://youtu.be/dQw4w9WgXcQ?si=x").unwrap(),
        "dQw4w9WgXcQ"
    );
    assert_eq!(
        video_id_from_url("https://www.youtube.com/shorts/dQw4w9WgXcQ").unwrap(),
        "dQw4w9WgXcQ"
    );
    assert_eq!(video_id_from_url("dQw4w9WgXcQ").unwrap(), "dQw4w9WgXcQ");
}

#[test]
fn rejects_non_youtube_urls() {
    assert!(video_id_from_url("https://example.com/watch?v=dQw4w9WgXcQ").is_err());
}

#[test]
fn extracts_player_response_json_from_html() {
    let html = r#"<script>var ytInitialPlayerResponse = {"videoDetails":{"title":"Hi \"there\""}};</script>"#;
    let player = player_response_from_html(html).unwrap();
    assert_eq!(player["videoDetails"]["title"], "Hi \"there\"");
}

#[test]
fn returns_manual_and_auto_tracks() {
    let player = json!({
        "captions": {
            "playerCaptionsTracklistRenderer": {
                "captionTracks": [
                    {
                        "baseUrl": "https://www.youtube.com/api/timedtext?a=1",
                        "languageCode": "en",
                        "name": { "simpleText": "English" }
                    },
                    {
                        "baseUrl": "https://www.youtube.com/api/timedtext?a=2",
                        "languageCode": "de",
                        "kind": "asr",
                        "name": { "runs": [{ "text": "German" }] }
                    }
                ]
            }
        }
    });
    let tracks = tracks_from_player(&player);
    assert_eq!(tracks.len(), 2);
    assert_eq!(tracks[0]["label"], "English");
    assert_eq!(tracks[0]["isAutoGenerated"], false);
    assert_eq!(tracks[1]["label"], "German");
    assert_eq!(tracks[1]["isAutoGenerated"], true);
}

#[test]
fn caption_body_to_text_parses_vtt_and_xml() {
    let vtt = "WEBVTT\n\n00:00:01.000 --> 00:00:02.000\nHello <i>world</i>\n";
    assert_eq!(caption_body_to_text(vtt).unwrap(), "Hello world");

    let xml = r#"<transcript><text start="1" dur="2">Tom &amp; Jerry</text><text start="3" dur="2">Hi</text></transcript>"#;
    assert_eq!(caption_body_to_text(xml).unwrap(), "Tom & Jerry\nHi");
}

#[test]
fn format_caption_url_replaces_existing_format() {
    let url = format_caption_url("https://www.youtube.com/api/timedtext?v=x&fmt=json3&lang=en");
    assert!(url.contains("fmt=vtt"));
    assert!(!url.contains("fmt=json3"));
}

#[test]
fn ytdlp_track_language_prefers_language_code_and_falls_back_to_vssid() {
    let track = json!({ "languageCode": "en", "vssId": "a.de" });
    assert_eq!(ytdlp_track_language(&track).as_deref(), Some("en"));

    let track = json!({ "vssId": ".pl" });
    assert_eq!(ytdlp_track_language(&track).as_deref(), Some("pl"));
}

#[test]
fn find_subtitle_file_finds_ytdlp_vtt_output() {
    let temp = tempfile::tempdir().unwrap();
    let path = temp.path().join("video.en.vtt");
    std::fs::write(&path, "WEBVTT\n\n00:00:01.000 --> 00:00:02.000\nHi\n").unwrap();
    assert_eq!(find_subtitle_file(temp.path()).unwrap(), Some(path));
}
