import { state } from "../state.js";
import { t } from "../i18n.js";
import { showToast } from "../toast.js";
import { isAndroidPlatform, isImageOcrAvailable } from "../platform.js";
import { fetchWithTimeout } from "../request.js";
import { decodeImportedTextBytes, parseImportedTextFile, titleFromImportedFileName } from "../subtitles.js";
import {
  cancelEditBook,
  importCustomText,
  isEditBookDirty,
  pasteImageToEditBook,
  saveEditedBook,
  updateEditBookCounter,
  wrapEditBookSelection
} from "../book-actions.js";
import { registerUnsavedDialog } from "../dialog-backdrop.js";
import { beginElementBusy, setElementBusy } from "../loading.js";
import { deleteStoredText } from "../store-bridge.js";
import { effectiveLearningLanguage } from "../translator-preferences.js";
import { isOcrImageFile, validatedOcrImageFormat } from "../ocr-image-format.js";

type ImportMeta = {
  author?: string;
  tags?: string;
  level?: string;
  source?: string;
  sourceUrl?: string;
  textUrl?: string;
  coverDataUrl?: string | null;
};

type YoutubeTrack = {
  index: string | number;
  label?: string;
  languageCode?: string;
  isAutoGenerated?: boolean;
};

type YoutubeCaptionsPayload =
  | { op: "tracks"; url: string }
  | { op: "download"; url: string; track_index: number };

type YoutubeCaptionsResponse = {
  tracks?: YoutubeTrack[];
  text?: string;
  title?: string;
  author?: string;
  thumbnailUrl?: string;
  sourceUrl?: string;
};

type AndroidPdfRenderResponse = {
  success: boolean;
  error?: string;
  dataUrl?: string;
};

type PdfOcrPage = WhRecord & {
  text?: string;
  imageName?: string;
};

type PdfImportResponse = {
  title?: string;
  text?: string;
  pages?: PdfOcrPage[];
  pageCount?: number;
  ocrEngine?: string;
  truncated?: boolean;
};

type EbookImportResponse = {
  title?: string;
  author?: string;
  text?: string;
  coverDataUrl?: string;
};

type ClipboardEventWithOriginal = ClipboardEvent & {
  originalEvent?: ClipboardEvent;
};

let pendingCoverDataUrl: string | null = "";
let pendingImportMeta: ImportMeta = {};
let youtubeTracks: YoutubeTrack[] = [];
let youtubeTracksUrl = "";
const MAX_DESKTOP_PDF_BYTES = 256 * 1024 * 1024;
const MAX_POCKET_PDF_BYTES = 32 * 1024 * 1024;
// The native Pocket bridge rejects base64 payloads above this cap BEFORE any
// decode (see ANDROID_PDF_MAX_BASE64_DECODED in MainActivity.kt), so a huge
// string is never materialized on the Java heap. Guard here as well, before
// the payload crosses the bridge at all.
const ANDROID_PDF_RENDER_MAX_BASE64_MB = 64;
const ANDROID_PDF_RENDER_MAX_BASE64_ENCODED = ANDROID_PDF_RENDER_MAX_BASE64_MB * 1024 * 1024 * 4 / 3 + 4;
/**
 * Rendering each PDF page synchronously on the JavaBridge stalls the JS
 * renderer ~100–500 ms per page. A 2000-page book would freeze the UI for
 * dozens of minutes, so Android overlay rendering is capped here (and the
 * page loop yields between pages so the spinner keeps painting).
 */
const MAX_POCKET_PDF_RENDER_PAGES = 300;
// Render at the screen width (device pixels) so small phones do not
// allocate 1400px bitmaps, clamped to the native renderer range.
function pdfRenderWidth(): number {
  const width = typeof window !== "undefined" && window.devicePixelRatio
    ? Math.round(window.innerWidth * window.devicePixelRatio)
    : 1400;
  return Math.min(2400, Math.max(512, width));
}
const MAX_DESKTOP_OCR_IMAGE_BYTES = 32 * 1024 * 1024;
const MAX_DESKTOP_IMPORT_FILE_BYTES = 64 * 1024 * 1024;
const MAX_POCKET_IMPORT_FILE_BYTES = 24 * 1024 * 1024;
const MAX_SERIALIZED_IMPORT_TEXT_BYTES = 96 * 1024 * 1024;
const POCKET_PDF_SCAN_ERROR = "PDF_TEXT_LAYER_EMPTY";
let ocrImportRunning = false;

/** Typed document lookup (import panel markup is TS-rendered since #127 P2). */
function el<T extends HTMLElement>(id: string): T | null {
  return document.getElementById(id) as T | null;
}

/**
 * Builds the library import panel (port of #127 P2: the static <aside> moved
 * from index.html into this renderer). Idempotent; appends into the library
 * workspace grid so the panel keeps its grid column position.
 */
export function renderImportPanel(): HTMLElement {
  const existing = document.getElementById("import-panel");
  if (existing) return existing;
  const host = document.querySelector(".workspace-grid.library-layout");
  if (!host) throw new TypeError("Missing library workspace grid for import panel");
  const panel = document.createElement("aside");
  panel.id = "import-panel";
  panel.className = "panel import-panel";
  panel.setAttribute("aria-labelledby", "import-heading");
  panel.innerHTML = `
    <div class="panel-header stacked">
      <p class="eyebrow" data-i18n="import.eyebrow">Custom text</p>
      <h2 id="import-heading" data-i18n="import.heading">Import</h2>
      <button type="button" id="library-import-close" class="icon-button pocket-drawer-close" data-i18n-attr="title=reader.close,aria-label=reader.close" aria-label="Close">×</button>
    </div>
    <div class="import-mode-row">
      <label for="import-mode-select">
        <span data-i18n="import.modeLabel">Import type</span>
        <select id="import-mode-select" class="input">
          <option value="books" data-i18n="import.modeBooks">Import books / texts</option>
          <option value="youtube" data-i18n="import.modeYoutube">Import YouTube subtitles</option>
        </select>
      </label>
    </div>
    <div id="import-books-mode">
      <form id="import-form" class="import-form">
        <label class="file-button">
          <span data-i18n="import.fileLabel">Import books / texts</span>
          <input id="import-file" type="file" accept=".txt,.md,.markdown,.srt,.vtt,.ass,.ssa,.epub,.mobi,.azw,.azw3,.pdf,text/plain,text/markdown,text/vtt,application/epub+zip,application/x-mobipocket-ebook,application/pdf">
        </label>
        <p class="muted-copy" id="import-file-hint" data-i18n-html="import.desktopOcrUnavailableFileHint"></p>
        <label>
          <span data-i18n="import.title">Title</span>
          <input id="import-title" type="text" data-i18n-attr="placeholder=import.titlePlaceholder" required>
        </label>
        <label>
          <span data-i18n="import.author">Author (optional)</span>
          <input id="import-author" type="text" data-i18n-attr="placeholder=import.authorPlaceholder">
        </label>
        <label>
          <span data-i18n="import.tags">Tags (optional)</span>
          <input id="import-tags" type="text" data-i18n-attr="placeholder=import.tagsPlaceholder">
        </label>
        <label>
          <span data-i18n="import.level">Level (optional)</span>
          <select id="import-level">
            <option value="" data-i18n="library.levelAny">Any</option>
            <option value="A1">A1</option>
            <option value="A2">A2</option>
            <option value="B1">B1</option>
            <option value="B2">B2</option>
            <option value="C1">C1</option>
            <option value="C2">C2</option>
          </select>
        </label>
        <label>
          <span data-i18n="import.text">Text</span>
          <textarea id="import-text" rows="10" spellcheck="false" data-i18n-attr="placeholder=import.textPlaceholder" required></textarea>
        </label>
        <div class="form-group m-b-15-center">
          <label for="import-cover" class="import-cover-dropzone dropzone" id="import-cover-dropzone" data-i18n-attr="title=import.cover">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="size-32-muted-m-b-05"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect><circle cx="8.5" cy="8.5" r="1.5"></circle><polyline points="21 15 16 10 5 21"></polyline></svg>
            <span data-i18n="import.coverPasteHint" class="fs-09-muted">Click to select or paste</span>
            <input id="import-cover" type="file" accept="image/*" class="visually-hidden">
          </label>
        </div>
        <div id="import-cover-preview" class="import-cover-preview m-b-15-w-max" hidden>
          <img id="import-cover-img" data-i18n-attr="alt=import.coverPreviewAlt" alt="Cover preview" class="max-h-150">
          <button type="button" id="import-cover-clear" data-i18n-attr="title=editBook.deleteCover" class="badge-remove">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="size-14"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
          </button>
        </div>
        <button class="primary-button" type="submit" id="import-submit" data-i18n="import.submit">Add to library</button>
      </form>
    </div>
    <div id="import-youtube-mode" hidden>
      <section class="youtube-import-section" aria-labelledby="youtube-import-heading">
        <h3 id="youtube-import-heading" data-i18n="import.youtubeHeading">YouTube subtitles</h3>
        <label>
          <span data-i18n="import.youtubeUrl">YouTube URL</span>
          <input id="import-youtube-url" type="url" data-i18n-attr="placeholder=import.youtubePlaceholder">
        </label>
        <div class="youtube-import-actions">
          <select id="import-youtube-track" hidden data-i18n-attr="aria-label=import.youtubeTrack"></select>
          <button class="secondary-button" type="button" id="import-youtube-load" data-i18n="import.youtubeLoad">Load subtitles</button>
        </div>
        <p class="muted-copy" id="import-youtube-status" aria-live="polite"></p>
      </section>
    </div>
  `;
  host.appendChild(panel);
  return panel;
}


function resetCoverPreview() {
  pendingCoverDataUrl = "";
  const coverImg = el<HTMLImageElement>("import-cover-img");
  if (coverImg) coverImg.src = "";
  const coverPreview = el<HTMLElement>("import-cover-preview");
  if (coverPreview) coverPreview.hidden = true;
  const cover = el<HTMLInputElement>("import-cover");
  if (cover) cover.value = "";
  const dropzone = document.getElementById("import-cover-dropzone");
  if (dropzone) dropzone.style.display = "flex";
}

function setImportCoverPreview(dataUrl: string): void {
  pendingCoverDataUrl = dataUrl || "";
  const coverImg = el<HTMLImageElement>("import-cover-img");
  if (coverImg) coverImg.src = pendingCoverDataUrl;
  const coverPreview = el<HTMLElement>("import-cover-preview");
  if (coverPreview) coverPreview.hidden = !pendingCoverDataUrl;
  const dropzone = document.getElementById("import-cover-dropzone");
  if (dropzone) dropzone.style.display = pendingCoverDataUrl ? "none" : "flex";
}

function clearPendingImportMeta() {
  pendingImportMeta = {};
}

function isEbookFile(file: File | null | undefined): boolean {
  return /\.(epub|mobi|azw|azw3)$/i.test(file?.name || "");
}

function isPdfFile(file: File | null | undefined): boolean {
  return file?.type === "application/pdf" || /\.pdf$/i.test(file?.name || "");
}

function safeImportErrorMessage(error: unknown): string {
  const message = error instanceof Error ? error.message.trim() : "";
  if (/PaddleOCR did not find readable text in this image/i.test(message)) return t("toast.imageOcrNoText");
  if (/Image is too large/i.test(message)) {
    return t("toast.imageTooLarge", { mb: Math.floor(MAX_DESKTOP_OCR_IMAGE_BYTES / (1024 * 1024)) });
  }
  if (/unsupported.*image|image.*does not match/i.test(message)) return t("toast.imageOcrUnsupported");
  if (/Image OCR requires the bundled PaddleOCR component/i.test(message)) return t("toast.imageOcrRequiresApp");
  if (/yt-dlp|\[youtube\]|video (?:unavailable|not found)|private video|sign in to confirm/i.test(message)) return t("import.youtubeError");
  const localizedMessages = new Set([
    t("toast.pdfImportBusy"),
    t("toast.pdfOcrRequiresApp"),
    t("toast.pdfTooLarge", { mb: Math.floor(MAX_POCKET_PDF_BYTES / (1024 * 1024)) }),
    t("toast.pdfTooLarge", { mb: Math.floor(MAX_DESKTOP_PDF_BYTES / (1024 * 1024)) }),
    t("toast.pdfTooLarge", { mb: ANDROID_PDF_RENDER_MAX_BASE64_MB }),
    t("toast.pdfOcrNoText"),
    t("toast.imageOcrRequiresApp"),
    t("toast.imageOcrNoText"),
    t("toast.imageOcrUnsupported"),
    t("toast.imageTooLarge", { mb: Math.floor(MAX_DESKTOP_OCR_IMAGE_BYTES / (1024 * 1024)) }),
    t("toast.importFailed"),
    t("toast.ebookRequiresApp"),
    t("toast.importedEbookEmpty"),
    t("toast.importedFileEmpty"),
    t("toast.importFileTooLarge", { mb: Math.floor(MAX_POCKET_IMPORT_FILE_BYTES / (1024 * 1024)) }),
    t("toast.importFileTooLarge", { mb: Math.floor(MAX_DESKTOP_IMPORT_FILE_BYTES / (1024 * 1024)) })
  ]);
  return localizedMessages.has(message) ? message : t("toast.fileError");
}

function slugFromFileName(name: string): string | number {
  const base = titleFromImportedFileName(name || t("import.importedPdfTitle"));
  return base.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || Date.now();
}

async function readFileAsBase64(file: Blob): Promise<string> {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.addEventListener("load", () => resolve(String(reader.result || "")), { once: true });
    reader.addEventListener("error", () => reject(reader.error || new Error("Could not read file")), { once: true });
    reader.readAsDataURL(file);
  });
}

function parseAndroidPdfRenderResponse(raw: unknown, fallbackMessage: string): AndroidPdfRenderResponse {
  let payload: AndroidPdfRenderResponse;
  try {
    payload = JSON.parse(String(raw || "")) as AndroidPdfRenderResponse;
  } catch {
    throw new Error(fallbackMessage);
  }
  if (!payload?.success) {
    throw new Error(payload?.error || fallbackMessage);
  }
  return payload;
}

function getAndroidPdfRendererBridge(): WhAndroidBridge | null {
  const bridge = window.WordHunterAndroid;
  if (!bridge || typeof bridge.beginPdfRender !== "function" || typeof bridge.renderPdfPage !== "function") {
    return null;
  }
  return bridge;
}

async function renderAndSaveAndroidPdfPages(data: string, bookId: string, pages: PdfOcrPage[]): Promise<void> {
  if (!isAndroidPlatform() || !pages.length) return;
  const bridge = getAndroidPdfRendererBridge();
  if (!bridge) throw new Error(t("toast.pdfOcrRequiresApp"));

  const limitedPages = pages.slice(0, MAX_POCKET_PDF_RENDER_PAGES);
  if (data.length > ANDROID_PDF_RENDER_MAX_BASE64_ENCODED) {
    throw new Error(t("toast.pdfTooLarge", { mb: ANDROID_PDF_RENDER_MAX_BASE64_MB }));
  }
  const sessionId = `wh-pdf-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  parseAndroidPdfRenderResponse(
    bridge.beginPdfRender(sessionId, data),
    t("toast.pdfOcrNoText")
  );
  try {
    for (let index = 0; index < limitedPages.length; index += 1) {
      if (androidPdfRenderCancelled) throw new Error("android pdf render cancelled");
      // Yield between synchronous bridge renders so the UI keeps painting
      // (spinner, progress) instead of freezing for the whole import.
      await waitForUiPaint();
      updateAndroidPdfProgress(index + 1, limitedPages.length);
      const page = limitedPages[index];
      const rendered = parseAndroidPdfRenderResponse(
        bridge.renderPdfPage(sessionId, index, pdfRenderWidth()),
        t("toast.pdfOcrNoText")
      );
      if (!rendered.dataUrl || !page?.imageName) {
        throw new Error(t("toast.pdfOcrNoText"));
      }
      const response = await fetchWithTimeout("/__book/image", {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-WH-Token": window.WH_TOKEN || "" },
        body: JSON.stringify({
          book_id: bookId,
          img_name: page.imageName,
          base64_data: rendered.dataUrl,
          pending_import: true
        })
      }, 30_000);
      if (!response.ok) {
        const message = await response.text().catch(() => "");
        throw new Error(message || `HTTP ${response.status}`);
      }
    }
  } finally {
    if (typeof bridge.endPdfRender === "function") bridge.endPdfRender(sessionId);
  }
}

function setImportLoading(visible: boolean, messageKey = "import.parsingEbook"): void {
  let overlay = document.getElementById("import-loading");
  if (visible) {
    if (!overlay) {
      overlay = document.createElement("div");
      overlay.id = "import-loading";
      overlay.className = "section-loading";
      const form = document.getElementById("import-form");
      if (form) form.style.position = "relative", form.appendChild(overlay);
    }
    overlay.setAttribute("role", "status");
    overlay.setAttribute("aria-live", "polite");
    overlay.setAttribute("aria-atomic", "true");
    overlay.innerHTML = `<div class="spinner" aria-hidden="true"></div><p class="muted-copy">${t(messageKey)}</p>`;
    overlay.hidden = false;
  } else {
    const ov = document.getElementById("import-loading");
    if (ov) ov.hidden = true;
  }
  setElementBusy(document.getElementById("import-form"), visible);
}

let _ocrTimerHandle: number | null = null;
let androidPdfRenderCancelled = false;
let _androidPdfProgressTimer: number | null = null;

function startAndroidPdfProgress(total: number, onCancel: () => void): void {
  stopOcrProgress();
  const overlay = document.getElementById("import-loading");
  if (!overlay) return;
  const startedAt = Date.now();
  overlay.innerHTML = `
    <div class="ocr-progress-card">
      <div class="ocr-progress-document" aria-hidden="true">
        <span></span><span></span><span></span><span></span>
        <i class="ocr-progress-scan-line"></i>
      </div>
      <div class="ocr-progress-copy">
        <p id="ocr-progress-text"></p>
        <p class="muted-copy ocr-progress-eta" id="ocr-progress-eta" aria-hidden="true"></p>
      </div>
      <div class="ocr-progress-bar" aria-hidden="true"><div class="ocr-progress-bar-fill"></div></div>
      <button class="secondary-button" type="button" id="ocr-cancel">${t("import.ocrCancel")}</button>
    </div>
  `;
  const textEl = () => overlay.querySelector<HTMLElement>("#ocr-progress-text");
  const etaEl = () => overlay.querySelector<HTMLElement>("#ocr-progress-eta");
  const fillEl = () => overlay.querySelector<HTMLElement>(".ocr-progress-bar-fill");
  const fmt = (sec: number): string => {
    const m = Math.floor(sec / 60);
    const s = Math.floor(sec % 60);
    return `${m}:${String(s).padStart(2, "0")}`;
  };
  const tick = () => {
    const elapsed = Math.floor((Date.now() - startedAt) / 1000);
    if (textEl()) textEl().textContent = t("import.pdfPageRenderProgress", { processed: 0, total });
    if (etaEl()) etaEl().textContent = t("import.pdfPageRenderStatus", { elapsed: fmt(elapsed) });
  };
  overlay.querySelector<HTMLButtonElement>("#ocr-cancel")?.addEventListener("click", (event) => {
    (event.currentTarget as HTMLButtonElement).disabled = true;
    if (textEl()) textEl().textContent = t("import.ocrCancelling");
    stopOcrProgress();
    onCancel();
  });
  tick();
  _androidPdfProgressTimer = setInterval(tick, 1000);
}

function updateAndroidPdfProgress(processed: number, total: number): void {
  const overlay = document.getElementById("import-loading");
  if (!overlay) return;
  const textEl = overlay.querySelector<HTMLElement>("#ocr-progress-text");
  const fillEl = overlay.querySelector<HTMLElement>(".ocr-progress-bar-fill");
  if (textEl) textEl.textContent = t("import.pdfPageRenderProgress", { processed, total });
  if (fillEl && total > 0) {
    fillEl.style.width = `${Math.round((processed / total) * 100)}%`;
  }
}

function stopAndroidPdfProgress(): void {
  if (_androidPdfProgressTimer !== null) {
    clearInterval(_androidPdfProgressTimer);
    _androidPdfProgressTimer = null;
  }
}

function waitForUiPaint(): Promise<void> {
  if (typeof requestAnimationFrame !== "function") return Promise.resolve();
  return new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve())));
}

function startOcrProgress(messageKey: string, statusKey: string, onCancel: () => void): void {
  stopOcrProgress();
  const overlay = document.getElementById("import-loading");
  if (!overlay) return;
  const startedAt = Date.now();
  overlay.innerHTML = `
    <div class="ocr-progress-card">
      <div class="ocr-progress-document" aria-hidden="true">
        <span></span><span></span><span></span><span></span>
        <i class="ocr-progress-scan-line"></i>
      </div>
      <div class="ocr-progress-copy">
        <p id="ocr-progress-text"></p>
        <p class="muted-copy ocr-progress-eta" id="ocr-progress-eta" aria-hidden="true"></p>
      </div>
      <div class="ocr-progress-bar" aria-hidden="true"><div class="ocr-progress-bar-fill"></div></div>
      <button class="secondary-button" type="button" id="ocr-cancel">${t("import.ocrCancel")}</button>
    </div>
  `;
  const textEl = () => overlay.querySelector<HTMLElement>("#ocr-progress-text");
  const etaEl = () => overlay.querySelector<HTMLElement>("#ocr-progress-eta");
  const fmt = (sec: number): string => {
    const m = Math.floor(sec / 60);
    const s = Math.floor(sec % 60);
    return `${m}:${String(s).padStart(2, "0")}`;
  };
  const tick = () => {
    const elapsed = Math.floor((Date.now() - startedAt) / 1000);
    if (textEl()) textEl().textContent = t(messageKey);
    if (etaEl()) etaEl().textContent = t(statusKey, { elapsed: fmt(elapsed) });
  };
  overlay.querySelector<HTMLButtonElement>("#ocr-cancel")?.addEventListener("click", (event) => {
    (event.currentTarget as HTMLButtonElement).disabled = true;
    if (textEl()) textEl().textContent = t("import.ocrCancelling");
    stopOcrProgress();
    onCancel();
  });
  tick();
  _ocrTimerHandle = setInterval(tick, 1000);
}

function stopOcrProgress() {
  if (_ocrTimerHandle) {
    clearInterval(_ocrTimerHandle);
    _ocrTimerHandle = null;
  }
}

function setYoutubeImportLoading(loading: boolean, statusKey = "import.youtubeLoading"): void {
  const importYoutubeLoad = el<HTMLButtonElement>("import-youtube-load");
  if (importYoutubeLoad) {
    setElementBusy(importYoutubeLoad, loading, { disable: true });
    importYoutubeLoad.textContent = t(loading ? statusKey : (youtubeTracks.length ? "import.youtubeImportSelected" : "import.youtubeLoad"));
  }
  if (loading) {
    const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
    if (importYoutubeStatus) importYoutubeStatus.textContent = t(statusKey);
  }
}

function resetYoutubeTracks(clearUrl = false) {
  youtubeTracks = [];
  youtubeTracksUrl = "";
  if (clearUrl) {
    const importYoutubeUrl = el<HTMLInputElement>("import-youtube-url");
    if (importYoutubeUrl) importYoutubeUrl.value = "";
  }
  const importYoutubeTrack = el<HTMLSelectElement>("import-youtube-track");
  if (importYoutubeTrack) {
    importYoutubeTrack.innerHTML = "";
    importYoutubeTrack.hidden = true;
  }
  const importYoutubeLoad = el<HTMLButtonElement>("import-youtube-load");
  if (importYoutubeLoad) importYoutubeLoad.textContent = t("import.youtubeLoad");
  const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
  if (importYoutubeStatus) importYoutubeStatus.textContent = "";
}

async function youtubeCaptionsRequest(payload: YoutubeCaptionsPayload): Promise<YoutubeCaptionsResponse> {
  const response = await fetch("/__youtube/captions", {
    method: "POST",
    headers: { "Content-Type": "application/json", "X-WH-Token": window.WH_TOKEN || "" },
    body: JSON.stringify(payload)
  });
  if (!response.ok) {
    const message = await response.text().catch(() => "");
    throw new Error(message || `HTTP ${response.status}`);
  }
  return response.json() as Promise<YoutubeCaptionsResponse>;
}

function youtubeTrackLabel(track: YoutubeTrack): string {
  const label = track.label || track.languageCode || t("import.youtubeUnknownLanguage");
  const suffix = track.isAutoGenerated ? t("import.youtubeAutoTrack") : t("import.youtubeManualTrack");
  return `${label} · ${suffix}`;
}

async function loadYoutubeTracks(url: string): Promise<YoutubeTrack | null> {
  setYoutubeImportLoading(true, "import.youtubeLoading");
  const data = await youtubeCaptionsRequest({ op: "tracks", url });
  youtubeTracks = Array.isArray(data.tracks) ? data.tracks : [];
  youtubeTracksUrl = url;
  if (!youtubeTracks.length) {
    resetYoutubeTracks(false);
    const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
    if (importYoutubeStatus) importYoutubeStatus.textContent = t("import.youtubeNoTracks");
    return null;
  }
  const importYoutubeTrack = el<HTMLSelectElement>("import-youtube-track");
  if (importYoutubeTrack) {
    importYoutubeTrack.replaceChildren(
      ...youtubeTracks.map((track) => new Option(youtubeTrackLabel(track), String(track.index)))
    );
    importYoutubeTrack.hidden = youtubeTracks.length < 2;
  }
  const importYoutubeLoad = el<HTMLButtonElement>("import-youtube-load");
  if (importYoutubeLoad) importYoutubeLoad.textContent = t("import.youtubeImportSelected");
  if (youtubeTracks.length > 1) {
    const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
    if (importYoutubeStatus) importYoutubeStatus.textContent = t("import.youtubeChooseTrack", { count: youtubeTracks.length });
    return null;
  }
  return youtubeTracks[0];
}

async function importYoutubeTrack(url: string, trackIndex: string | number): Promise<void> {
  setYoutubeImportLoading(true, "import.youtubeImporting");
  const data = await youtubeCaptionsRequest({ op: "download", url, track_index: Number(trackIndex) });
  if (!data.text) throw new Error(t("import.youtubeNoText"));
  const importText = el<HTMLTextAreaElement>("import-text");
  if (importText) importText.value = data.text;
  const importTitle = el<HTMLInputElement>("import-title");
  if (importTitle && !importTitle.value.trim()) importTitle.value = data.title || t("import.youtubeImportedTitle");
  const importAuthor = el<HTMLInputElement>("import-author");
  if (importAuthor && !importAuthor.value.trim()) importAuthor.value = data.author || "";
  setImportCoverPreview(data.thumbnailUrl || "");
  pendingImportMeta = {
    source: t("import.youtubeSource"),
    sourceUrl: data.sourceUrl || url,
    textUrl: data.sourceUrl || url
  };
  const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
  if (importYoutubeStatus) importYoutubeStatus.textContent = t("import.youtubeLoaded");
  showToast(t("toast.youtubeCaptionsLoaded"));
  // The captions are now in the books form — switch back so the user can
  // review and submit the import.
  const importModeSelect = el<HTMLSelectElement>("import-mode-select");
  if (importModeSelect) importModeSelect.value = "books";
  const importBooksMode = el<HTMLElement>("import-books-mode");
  if (importBooksMode) importBooksMode.hidden = false;
  const importYoutubeMode = el<HTMLElement>("import-youtube-mode");
  if (importYoutubeMode) importYoutubeMode.hidden = true;
}

async function handleYoutubeImport() {
  const url = el<HTMLInputElement>("import-youtube-url")?.value.trim();
  if (!url) {
    const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
    if (importYoutubeStatus) importYoutubeStatus.textContent = t("import.youtubeMissingUrl");
    return;
  }
  try {
    if (!youtubeTracks.length || youtubeTracksUrl !== url) {
      const onlyTrack = await loadYoutubeTracks(url);
      if (!onlyTrack) return;
      await importYoutubeTrack(url, onlyTrack.index);
      return;
    }
    const selectedIndex = el<HTMLSelectElement>("import-youtube-track")?.value || youtubeTracks[0]?.index;
    await importYoutubeTrack(url, selectedIndex);
  } catch (error) {
    console.warn(error);
    resetYoutubeTracks(false);
    const message = error instanceof Error && error.message.trim()
      ? safeImportErrorMessage(error)
      : t("import.youtubeError");
    const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
    if (importYoutubeStatus) importYoutubeStatus.textContent = message;
    showToast(t("toast.youtubeCaptionsError"));
  } finally {
    setYoutubeImportLoading(false);
  }
}

export function confirmWholeBookOcr(): Promise<boolean> {
  let dialog = document.querySelector<HTMLDialogElement>("#ocr-whole-book-confirm");
  if (dialog && (
    !dialog.querySelector("h2")
    || !dialog.querySelector("p")
    || !dialog.querySelector('[data-action="cancel"]')
    || !dialog.querySelector('[data-action="confirm"]')
  )) {
    // A stale/partially-restored dialog must not make the Promise executor
    // throw before it can settle. Rebuild the complete dialog instead.
    dialog.remove();
    dialog = null;
  }
  dialog ||= (() => {
    const next = document.createElement("dialog");
    next.id = "ocr-whole-book-confirm";
    next.className = "panel ocr-confirm-dialog";
    next.setAttribute("aria-labelledby", "ocr-whole-book-confirm-title");
    next.innerHTML = `
      <div class="panel-header"><h2 id="ocr-whole-book-confirm-title">${t("import.ocrWholeBookTitle")}</h2></div>
      <div class="ocr-confirm-body">
        <p class="muted-copy">${t("import.ocrWholeBookConfirm")}</p>
        <div class="ocr-confirm-actions">
          <button class="secondary-button" type="button" data-action="cancel">${t("import.ocrWholeBookCancel")}</button>
          <button class="primary-button" type="button" data-action="confirm">${t("import.ocrWholeBookStart")}</button>
        </div>
      </div>`;
    document.body.appendChild(next);
    return next;
  })();
  const heading = dialog.querySelector<HTMLElement>("h2");
  const copy = dialog.querySelector<HTMLElement>("p");
  const cancelButton = dialog.querySelector<HTMLButtonElement>('[data-action="cancel"]');
  const confirmButton = dialog.querySelector<HTMLButtonElement>('[data-action="confirm"]');
  if (!heading || !copy || !cancelButton || !confirmButton) {
    dialog.remove();
    return Promise.resolve(false);
  }
  heading.textContent = t("import.ocrWholeBookTitle");
  copy.textContent = t("import.ocrWholeBookConfirm");
  cancelButton.textContent = t("import.ocrWholeBookCancel");
  confirmButton.textContent = t("import.ocrWholeBookStart");

  return new Promise<boolean>((resolve) => {
    const finish = (accepted: boolean) => {
      if (dialog.open) dialog.close();
      dialog.removeEventListener("cancel", cancel);
      dialog.removeEventListener("click", backdrop);
      cancelButton.removeEventListener("click", cancel);
      confirmButton.removeEventListener("click", confirm);
      dialog.remove();
      resolve(accepted);
    };
    const cancel = (event?: Event) => { event?.preventDefault(); finish(false); };
    const confirm = () => finish(true);
    const backdrop = (event: MouseEvent) => { if (event.target === dialog) cancel(); };
    dialog.addEventListener("cancel", cancel);
    dialog.addEventListener("click", backdrop);
    cancelButton.addEventListener("click", cancel);
    confirmButton.addEventListener("click", confirm);
    dialog.showModal();
  });
}

function showPocketPdfScanDialog(): Promise<void> {
  const dialog = document.querySelector<HTMLDialogElement>("#pocket-pdf-scan-warning") || (() => {
    const next = document.createElement("dialog");
    next.id = "pocket-pdf-scan-warning";
    next.className = "panel ocr-confirm-dialog";
    next.setAttribute("aria-labelledby", "pocket-pdf-scan-warning-title");
    next.innerHTML = `
      <div class="panel-header"><h2 id="pocket-pdf-scan-warning-title"></h2></div>
      <div class="ocr-confirm-body">
        <p class="muted-copy"></p>
        <div class="ocr-confirm-actions">
          <button class="primary-button" type="button" data-action="close"></button>
        </div>
      </div>`;
    document.body.appendChild(next);
    return next;
  })();
  dialog.querySelector("h2").textContent = t("import.pdfPocketScanTitle");
  dialog.querySelector("p").textContent = t("import.pdfPocketScanBody");
  dialog.querySelector('[data-action="close"]').textContent = t("reader.close");

  return new Promise<void>((resolve) => {
    const finish = (event?: Event) => {
      event?.preventDefault();
      dialog.close();
      dialog.removeEventListener("cancel", finish);
      closeButton.removeEventListener("click", finish);
      resolve();
    };
    const closeButton = dialog.querySelector<HTMLButtonElement>('[data-action="close"]');
    dialog.addEventListener("cancel", finish);
    closeButton.addEventListener("click", finish);
    dialog.showModal();
  });
}

async function importPdfFile(file: File): Promise<boolean> {
  if (ocrImportRunning) throw new Error(t("toast.pdfImportBusy"));
  ocrImportRunning = true;
  try {
    return await runPdfImport(file);
  } catch (error) {
    if (error?.message === POCKET_PDF_SCAN_ERROR) {
      await showPocketPdfScanDialog();
      return false;
    }
    throw error;
  } finally {
    ocrImportRunning = false;
  }
}

async function runPdfImport(file: File): Promise<boolean> {
  const androidPdfOverlay = isAndroidPlatform();
  if (!window.__qtBridge && !androidPdfOverlay) {
    throw new Error(t("toast.pdfOcrRequiresApp"));
  }
  const maxBytes = androidPdfOverlay ? MAX_POCKET_PDF_BYTES : MAX_DESKTOP_PDF_BYTES;
  if (Number(file?.size) > maxBytes) {
    throw new Error(t("toast.pdfTooLarge", { mb: Math.floor(maxBytes / (1024 * 1024)) }));
  }
  if (!androidPdfOverlay && !await confirmWholeBookOcr()) return false;
  const profile = state.preferences.learningLanguage || "en";
  const lang = effectiveLearningLanguage(state.preferences);
  const id = `${profile}-pdf-ocr-${slugFromFileName(file.name)}-${Date.now()}`;
  const jobId = crypto.randomUUID();
  const controller = new AbortController();
  let cancelled = false;
  let requestStarted = false;
  setImportLoading(true, androidPdfOverlay ? "import.parsingPdfTextLayer" : "import.parsingPdfOcr");
  if (!androidPdfOverlay) {
    startOcrProgress("import.parsingPdfOcr", "import.ocrWholeBookStatus", () => {
      cancelled = true;
      controller.abort();
      if (requestStarted) {
        void fetch("/__import/ocr/cancel", {
          method: "POST",
          headers: { "Content-Type": "application/json", "X-WH-Token": window.WH_TOKEN || "" },
          body: JSON.stringify({ job_id: jobId })
        }).catch((error) => console.warn("PDF OCR cancellation request failed", error));
      }
    });
  }
  try {
    if (!androidPdfOverlay) await waitForUiPaint();
    let data = null;
    const params = new URLSearchParams({
      book_id: id,
      job_id: jobId,
      filename: file.name || t("import.importedPdfTitle"),
      lang,
      max_pages: "0"
    });
    requestStarted = true;
    const response = await fetch(`/__import/pdf_ocr/raw?${params}`, {
      method: "POST",
      headers: { "Content-Type": "application/pdf", "X-WH-Token": window.WH_TOKEN || "" },
      signal: controller.signal,
      body: file
    });
    if (!response.ok) {
      const message = await response.text().catch(() => "");
      if (message.trim() === POCKET_PDF_SCAN_ERROR) {
        throw new Error(POCKET_PDF_SCAN_ERROR);
      }
      throw new Error(message || `HTTP ${response.status}`);
    }
    const imported = await response.json() as PdfImportResponse;
    const pages = Array.isArray(imported.pages) ? imported.pages : [];
    const text = imported.text || pages.map((page) => page.text || "").join("\n\n").trim();
    if (!text) throw new Error(t("toast.pdfOcrNoText"));
    const pageCount = imported.pageCount || pages.length;
    const ocrEngine = imported.ocrEngine || "PaddleOCR";
    const hasOverlayPages = pages.length > 0;
    if (androidPdfOverlay && hasOverlayPages) {
      androidPdfRenderCancelled = false;
      startAndroidPdfProgress(Math.min(pages.length, MAX_POCKET_PDF_RENDER_PAGES), () => {
        androidPdfRenderCancelled = true;
        cancelled = true;
      });
      data = await readFileAsBase64(file);
      await renderAndSaveAndroidPdfPages(data, id, pages);
      stopAndroidPdfProgress();
    }
    const blurb = androidPdfOverlay
      ? t("import.pdfTextLayerBlurb", { pages: pageCount })
      : hasOverlayPages
        ? imported.truncated
          ? t("import.pdfOcrBlurbTruncated", { processed: pages.length, total: pageCount, engine: ocrEngine })
          : t("import.pdfOcrBlurb", { pages: pages.length, engine: ocrEngine })
        : t("import.pdfTextLayerBlurb", { pages: pageCount });
    const importedId = await importCustomText(imported.title || titleFromImportedFileName(file.name || t("import.importedPdfTitle")), text, {
      id,
      blurb,
      coverDataUrl: hasOverlayPages && pages[0]?.imageName ? `/__media?book=${encodeURIComponent(id)}&img=${encodeURIComponent(pages[0].imageName)}` : "",
      pdfOcrPages: hasOverlayPages ? pages : undefined,
      pdfOcrEngine: hasOverlayPages ? ocrEngine : "",
      pdfOcrPageCount: hasOverlayPages ? pageCount : 0,
      experimental: hasOverlayPages
    });
    if (!importedId) throw new Error(t("toast.importFailed"));
    return true;
  } catch (error) {
    await deleteStoredText(id).catch((cleanupError) => {
      console.warn("Failed to clean incomplete PDF import", cleanupError);
    });
    if (cancelled) {
      showToast(t("import.ocrCancelled"));
      return false;
    }
    throw error;
  } finally {
    // The render loop can throw (bridge error, cancel, network) — the
    // progress interval must never outlive the import (timer leak).
    stopAndroidPdfProgress();
    stopOcrProgress();
    setImportLoading(false);
  }
}

async function importOcrImageFile(file: File): Promise<boolean> {
  if (!isImageOcrAvailable() || !window.__qtBridge) {
    throw new Error(t("toast.imageOcrRequiresApp"));
  }
  if (ocrImportRunning) throw new Error(t("toast.pdfImportBusy"));
  const format = validatedOcrImageFormat(file);
  if (!format) throw new Error(t("toast.imageOcrUnsupported"));
  if (file.size > MAX_DESKTOP_OCR_IMAGE_BYTES) {
    throw new Error(t("toast.imageTooLarge", { mb: Math.floor(MAX_DESKTOP_OCR_IMAGE_BYTES / (1024 * 1024)) }));
  }
  ocrImportRunning = true;
  const profile = state.preferences.learningLanguage || "en";
  const id = `${profile}-image-ocr-${slugFromFileName(file.name)}-${Date.now()}`;
  const jobId = crypto.randomUUID();
  const controller = new AbortController();
  let cancelled = false;
  let requestStarted = false;
  setImportLoading(true, "import.parsingImageOcr");
  startOcrProgress("import.parsingImageOcr", "import.ocrImageStatus", () => {
    cancelled = true;
    controller.abort();
    if (requestStarted) {
      void fetch("/__import/ocr/cancel", {
        method: "POST",
        headers: { "Content-Type": "application/json", "X-WH-Token": window.WH_TOKEN || "" },
        body: JSON.stringify({ job_id: jobId })
      }).catch((error) => console.warn("Image OCR cancellation request failed", error));
    }
  });
  try {
    await waitForUiPaint();
    const params = new URLSearchParams({
      book_id: id,
      job_id: jobId,
      filename: file.name || t("import.importedImageTitle"),
      lang: effectiveLearningLanguage(state.preferences)
    });
    requestStarted = true;
    const response = await fetch(`/__import/image_ocr/raw?${params}`, {
      method: "POST",
      headers: { "Content-Type": format.contentType, "X-WH-Token": window.WH_TOKEN || "" },
      signal: controller.signal,
      body: file
    });
    if (!response.ok) {
      const message = await response.text().catch(() => "");
      throw new Error(message || `HTTP ${response.status}`);
    }
    const imported = await response.json() as PdfImportResponse;
    const pages = Array.isArray(imported.pages) ? imported.pages : [];
    const text = imported.text || pages.map((page) => page.text || "").join("\n\n").trim();
    if (!text || pages.length !== 1 || !pages[0]?.imageName) {
      throw new Error(t("toast.imageOcrNoText"));
    }
    const ocrEngine = imported.ocrEngine || "PaddleOCR";
    const importedId = await importCustomText(
      imported.title || titleFromImportedFileName(file.name || t("import.importedImageTitle")),
      text,
      {
        id,
        blurb: t("import.imageOcrBlurb", { engine: ocrEngine }),
        coverDataUrl: `/__media?book=${encodeURIComponent(id)}&img=${encodeURIComponent(pages[0].imageName)}`,
        pdfOcrPages: pages,
        pdfOcrEngine: ocrEngine,
        pdfOcrPageCount: 1,
        experimental: true
      }
    );
    if (!importedId) throw new Error(t("toast.importFailed"));
    return true;
  } catch (error) {
    await deleteStoredText(id).catch((cleanupError) => {
      console.warn("Failed to clean incomplete image OCR import", cleanupError);
    });
    if (cancelled) {
      showToast(t("import.ocrCancelled"));
      return false;
    }
    throw error;
  } finally {
    ocrImportRunning = false;
    stopOcrProgress();
    setImportLoading(false);
  }
}

async function importEbookFile(file: File): Promise<EbookImportResponse> {
  if (!window.__qtBridge) {
    throw new Error(t("toast.ebookRequiresApp"));
  }
  setImportLoading(true);
  try {
    const response = await fetch("/__import/ebook", {
      method: "POST",
      headers: { "Content-Type": "application/json", "X-WH-Token": window.WH_TOKEN || "" },
      body: JSON.stringify({ filename: file.name, data: await readFileAsBase64(file) })
    });
    if (!response.ok) {
      const message = await response.text().catch(() => "");
      throw new Error(message || `HTTP ${response.status}`);
    }
    return response.json() as Promise<EbookImportResponse>;
  } finally {
    setImportLoading(false);
  }
}

async function loadImportFile(file: File): Promise<boolean | void> {
  clearPendingImportMeta();
  resetYoutubeTracks(false);

  if (isPdfFile(file)) {
    return importPdfFile(file);
  }

  if (isOcrImageFile(file)) {
    return importOcrImageFile(file);
  }

  const maxImportBytes = isAndroidPlatform()
    ? MAX_POCKET_IMPORT_FILE_BYTES
    : MAX_DESKTOP_IMPORT_FILE_BYTES;
  if (file.size > maxImportBytes) {
    throw new Error(t("toast.importFileTooLarge", { mb: Math.floor(maxImportBytes / (1024 * 1024)) }));
  }

  if (isEbookFile(file)) {
    const ebook = await importEbookFile(file);
    if (!ebook.text) throw new Error(t("toast.importedEbookEmpty"));
    if (new TextEncoder().encode(JSON.stringify(ebook.text)).byteLength > MAX_SERIALIZED_IMPORT_TEXT_BYTES) {
      throw new Error(t("toast.importFileTooLarge", { mb: Math.floor(maxImportBytes / (1024 * 1024)) }));
    }
    const importText = el<HTMLTextAreaElement>("import-text");
    if (importText) importText.value = ebook.text;
    const importTitle = el<HTMLInputElement>("import-title");
    if (importTitle && !importTitle.value.trim()) importTitle.value = ebook.title || titleFromImportedFileName(file.name);
    const importAuthor = el<HTMLInputElement>("import-author");
    if (importAuthor && !importAuthor.value.trim()) importAuthor.value = ebook.author || "";
    setImportCoverPreview(ebook.coverDataUrl || "");
    return;
  }

  const rawText = decodeImportedTextBytes(
    await file.arrayBuffer(),
    effectiveLearningLanguage(state.preferences)
  );
  const text = parseImportedTextFile(file, rawText);
  if (!text) throw new Error(t("toast.importedFileEmpty"));
  if (new TextEncoder().encode(JSON.stringify(text)).byteLength > MAX_SERIALIZED_IMPORT_TEXT_BYTES) {
    throw new Error(t("toast.importFileTooLarge", { mb: Math.floor(maxImportBytes / (1024 * 1024)) }));
  }
  const importText = el<HTMLTextAreaElement>("import-text");
  if (importText) importText.value = text;
  const importTitle = el<HTMLInputElement>("import-title");
  if (importTitle && !importTitle.value.trim()) {
    importTitle.value = titleFromImportedFileName(file.name);
  }
}

function handleImportCoverFile(file: File | undefined): void {
  if (!file) return;
  if (file.size > 1_500_000) {
    showToast(t("toast.coverTooBig"));
    const importCover = el<HTMLInputElement>("import-cover");
    if (importCover) importCover.value = "";
    return;
  }
  const reader = new FileReader();
  reader.onload = () => { setImportCoverPreview(String(reader.result || "")); };
  reader.readAsDataURL(file);
}

function handleEditCoverFile(file: File | undefined): void {
  if (!file) return;
  if (file.size > 1_500_000) {
    showToast(t("toast.coverTooBig"));
    const editCoverInput = document.getElementById("edit-book-cover") as HTMLInputElement | null;
    if (editCoverInput) editCoverInput.value = "";
    return;
  }
  const reader = new FileReader();
  reader.onload = () => {
    const dataUrl = String(reader.result || "");
    import("../book-actions.js").then(m => m.setPendingEditCoverDataUrl(dataUrl));
    const editCoverImg = document.getElementById("edit-book-cover-img") as HTMLImageElement | null;
    if (editCoverImg) editCoverImg.src = dataUrl;
    const editCoverPreview = document.getElementById("edit-book-cover-preview");
    if (editCoverPreview) editCoverPreview.hidden = false;
    const dropzone = document.getElementById("edit-book-cover-dropzone");
    if (dropzone) dropzone.style.display = "none";
  };
  reader.readAsDataURL(file);
}

function bindImportFormEvents() {
  const importModeSelect = el<HTMLSelectElement>("import-mode-select");
  if (importModeSelect) {
    importModeSelect.addEventListener("change", () => {
      const mode = importModeSelect.value;
      const importBooksMode = el<HTMLElement>("import-books-mode");
      if (importBooksMode) importBooksMode.hidden = mode !== "books";
      const importYoutubeMode = el<HTMLElement>("import-youtube-mode");
      if (importYoutubeMode) importYoutubeMode.hidden = mode !== "youtube";
    });
  }

  const importYoutubeLoad = el<HTMLButtonElement>("import-youtube-load");
  if (importYoutubeLoad) {
    importYoutubeLoad.addEventListener("click", () => handleYoutubeImport());
  }

  const importYoutubeUrl = el<HTMLInputElement>("import-youtube-url");
  if (importYoutubeUrl) {
    importYoutubeUrl.addEventListener("input", () => {
      clearPendingImportMeta();
      resetYoutubeTracks(false);
    });
    importYoutubeUrl.addEventListener("keydown", (event) => {
      if (event.key === "Enter") {
        event.preventDefault();
        handleYoutubeImport();
      }
    });
  }

  const importFile = el<HTMLInputElement>("import-file");
  if (importFile) {
    importFile.addEventListener("change", async () => {
      const file = importFile.files?.[0];
      if (!file) return;
      const releaseBusy = beginElementBusy(importFile.closest?.(".file-button"));
      try {
        if (await loadImportFile(file) !== false) showToast(t("toast.fileLoaded", { name: file.name }));
      } catch (err) {
        console.warn(err);
        showToast(safeImportErrorMessage(err), "error");
      } finally {
        releaseBusy();
      }
    });
  }

  const importCover = el<HTMLInputElement>("import-cover");
  if (importCover) {
    importCover.addEventListener("change", () => handleImportCoverFile(importCover.files?.[0]));
  }

  const importCoverClear = el<HTMLButtonElement>("import-cover-clear");
  if (importCoverClear) {
    importCoverClear.addEventListener("click", () => {
      pendingCoverDataUrl = null;
      const coverImg = el<HTMLImageElement>("import-cover-img");
      if (coverImg) coverImg.src = "";
      const coverPreview = el<HTMLElement>("import-cover-preview");
      if (coverPreview) coverPreview.hidden = true;
      const coverInput = el<HTMLInputElement>("import-cover");
      if (coverInput) coverInput.value = "";
      const dropzone = document.getElementById("import-cover-dropzone");
      if (dropzone) dropzone.style.display = "flex";
    });
  }

  const importForm = el<HTMLFormElement>("import-form");
  if (importForm) {
    importForm.addEventListener("submit", async (event) => {
      event.preventDefault();
      const submitButton = event.submitter instanceof HTMLButtonElement
        ? event.submitter
        : document.querySelector<HTMLButtonElement>("#import-submit");
      if (submitButton?.disabled) return;
      const releaseButton = beginElementBusy(submitButton, { disable: true });
      const releaseForm = beginElementBusy(importForm);
      const meta: ImportMeta = {
        ...pendingImportMeta,
        author: el<HTMLInputElement>("import-author")?.value || pendingImportMeta.author,
        tags: el<HTMLInputElement>("import-tags")?.value,
        coverDataUrl: pendingCoverDataUrl
      };
      const levelVal = el<HTMLSelectElement>("import-level")?.value;
      if (levelVal) meta.level = levelVal;
      try {
        const importedId = await importCustomText(
          el<HTMLInputElement>("import-title")?.value || "",
          el<HTMLTextAreaElement>("import-text")?.value || "",
          meta
        );
        if (!importedId) return;
        importForm.reset();
        clearPendingImportMeta();
        resetYoutubeTracks(true);
        resetCoverPreview();
      } catch (e) {
        console.error("import custom text failed", e);
      } finally {
        releaseForm();
        releaseButton();
      }
    });
  }
}

function bindEditBookEvents() {
  registerUnsavedDialog("edit-book-dialog", isEditBookDirty, () => saveEditedBook(), () => cancelEditBook());
  const editBookDialog = document.getElementById("edit-book-dialog") as HTMLDialogElement | null;
  const editBookCancel = document.getElementById("edit-book-cancel") as HTMLButtonElement | null;
  const editBookSave = document.getElementById("edit-book-save") as HTMLButtonElement | null;
  const editBookCoverClear = document.getElementById("edit-book-cover-clear") as HTMLButtonElement | null;
  const editBookCover = document.getElementById("edit-book-cover") as HTMLInputElement | null;
  const editBookText = document.getElementById("edit-book-text") as HTMLTextAreaElement | null;
  if (editBookCancel) editBookCancel.addEventListener("click", () => cancelEditBook());
  if (editBookSave) editBookSave.addEventListener("click", () => saveEditedBook());

  const fmtBold = document.getElementById("edit-book-fmt-bold");
  const fmtItalic = document.getElementById("edit-book-fmt-italic");
  if (fmtBold) fmtBold.addEventListener("click", () => wrapEditBookSelection("**"));
  if (fmtItalic) fmtItalic.addEventListener("click", () => wrapEditBookSelection("*"));
  if (editBookText) {
    editBookText.addEventListener("input", updateEditBookCounter);
  }

  if (editBookDialog) {
    editBookDialog.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey && !(e.target instanceof HTMLTextAreaElement)
        && !(e.target instanceof HTMLSelectElement) && !(e.target instanceof HTMLButtonElement)) {
        e.preventDefault();
        saveEditedBook();
      }
    });
  }

  if (editBookCoverClear) {
    editBookCoverClear.addEventListener("click", () => {
      import("../book-actions.js").then(m => m.setPendingEditCoverDataUrl(null));
      const coverImg = document.getElementById("edit-book-cover-img") as HTMLImageElement | null;
      if (coverImg) coverImg.src = "";
      const coverPreview = document.getElementById("edit-book-cover-preview");
      if (coverPreview) coverPreview.hidden = true;
      const coverInput = document.getElementById("edit-book-cover") as HTMLInputElement | null;
      if (coverInput) coverInput.value = "";
      const dropzone = document.getElementById("edit-book-cover-dropzone");
      if (dropzone) dropzone.style.display = "flex";
    });
  }

  if (editBookCover) {
    editBookCover.addEventListener("change", () => handleEditCoverFile(editBookCover.files?.[0]));
  }

  if (editBookText) {
    editBookText.addEventListener("paste", (e) => {
      const clipboardEvent = e as ClipboardEventWithOriginal;
      const items = (clipboardEvent.clipboardData || clipboardEvent.originalEvent?.clipboardData)?.items;
      if (!items) return;
      for (const item of items) {
        if (item.type.indexOf("image") === 0) {
          const file = item.getAsFile();
          if (file) pasteImageToEditBook(file);
          e.preventDefault();
          e.stopPropagation();
        }
      }
    });
  }
}

function isTextEditingPasteTarget(target: EventTarget | null): boolean {
  return target instanceof Element && !!target.closest("textarea, input, [contenteditable='true']");
}

function bindCoverPasteEvents() {
  document.addEventListener("paste", (e) => {
    if (isTextEditingPasteTarget(e.target)) return;
    const importOpen = state.currentView === "library";
    const editOpen = (document.getElementById("edit-book-dialog") as HTMLDialogElement | null)?.open ?? false;
    if (!importOpen && !editOpen) return;
    const clipboardEvent = e as ClipboardEventWithOriginal;
    const items = (clipboardEvent.clipboardData || clipboardEvent.originalEvent?.clipboardData)?.items;
    if (!items) return;
    let handled = false;
    for (let index in items) {
      const item = items[index];
      if (item.kind === "file" && item.type.startsWith("image/")) {
        const file = item.getAsFile();
        if (file) {
          handled = true;
          if (editOpen) handleEditCoverFile(file);
          else if (importOpen) handleImportCoverFile(file);
        }
      }
    }
    if (handled) e.preventDefault();
  });
}

export function bindBookImportEvents() {
  bindImportFormEvents();
  bindEditBookEvents();
  bindCoverPasteEvents();
}
