// YouTube captions discovery + import flow.
import { t } from "../../i18n.js";
import { showToast } from "../../toast.js";
import { setElementBusy } from "../../loading.js";
import {
  clearPendingImportMeta,
  el,
  setImportCoverPreview,
  setImportLoading,
  setPendingImportMeta,
  safeImportErrorMessage,
} from "./shared.js";

let youtubeTracks: YoutubeTrack[] = [];
let youtubeTracksUrl = "";

type YoutubeTrack = {
  index: string | number;
  label?: string;
  languageCode?: string;
  isAutoGenerated?: boolean;
};

type YoutubeCaptionsPayload =
  | { op: "tracks"; url: string }
  | { op: "download"; url: string; track_index: number };

type YoutubeCaptionsResponse = {
  tracks?: YoutubeTrack[];
  text?: string;
  title?: string;
  author?: string;
  thumbnailUrl?: string;
  sourceUrl?: string;
};

function setYoutubeImportLoading(loading: boolean, statusKey = "import.youtubeLoading"): void {
  const importYoutubeLoad = el<HTMLButtonElement>("import-youtube-load");
  if (importYoutubeLoad) {
    setElementBusy(importYoutubeLoad, loading, { disable: true });
    importYoutubeLoad.textContent = t(loading ? statusKey : (youtubeTracks.length ? "import.youtubeImportSelected" : "import.youtubeLoad"));
  }
  if (loading) {
    const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
    if (importYoutubeStatus) importYoutubeStatus.textContent = t(statusKey);
  }
}

function resetYoutubeTracks(clearUrl = false) {
  youtubeTracks = [];
  youtubeTracksUrl = "";
  if (clearUrl) {
    const importYoutubeUrl = el<HTMLInputElement>("import-youtube-url");
    if (importYoutubeUrl) importYoutubeUrl.value = "";
  }
  const importYoutubeTrack = el<HTMLSelectElement>("import-youtube-track");
  if (importYoutubeTrack) {
    importYoutubeTrack.innerHTML = "";
    importYoutubeTrack.hidden = true;
  }
  const importYoutubeLoad = el<HTMLButtonElement>("import-youtube-load");
  if (importYoutubeLoad) importYoutubeLoad.textContent = t("import.youtubeLoad");
  const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
  if (importYoutubeStatus) importYoutubeStatus.textContent = "";
}

async function youtubeCaptionsRequest(payload: YoutubeCaptionsPayload): Promise<YoutubeCaptionsResponse> {
  const response = await fetch("/__youtube/captions", {
    method: "POST",
    headers: { "Content-Type": "application/json", "X-WH-Token": window.WH_TOKEN || "" },
    body: JSON.stringify(payload)
  });
  if (!response.ok) {
    const message = await response.text().catch(() => "");
    throw new Error(message || `HTTP ${response.status}`);
  }
  return response.json() as Promise<YoutubeCaptionsResponse>;
}

function youtubeTrackLabel(track: YoutubeTrack): string {
  const label = track.label || track.languageCode || t("import.youtubeUnknownLanguage");
  const suffix = track.isAutoGenerated ? t("import.youtubeAutoTrack") : t("import.youtubeManualTrack");
  return `${label} · ${suffix}`;
}

async function loadYoutubeTracks(url: string): Promise<YoutubeTrack | null> {
  setYoutubeImportLoading(true, "import.youtubeLoading");
  const data = await youtubeCaptionsRequest({ op: "tracks", url });
  youtubeTracks = Array.isArray(data.tracks) ? data.tracks : [];
  youtubeTracksUrl = url;
  if (!youtubeTracks.length) {
    resetYoutubeTracks(false);
    const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
    if (importYoutubeStatus) importYoutubeStatus.textContent = t("import.youtubeNoTracks");
    return null;
  }
  const importYoutubeTrack = el<HTMLSelectElement>("import-youtube-track");
  if (importYoutubeTrack) {
    importYoutubeTrack.replaceChildren(
      ...youtubeTracks.map((track) => new Option(youtubeTrackLabel(track), String(track.index)))
    );
    importYoutubeTrack.hidden = youtubeTracks.length < 2;
  }
  const importYoutubeLoad = el<HTMLButtonElement>("import-youtube-load");
  if (importYoutubeLoad) importYoutubeLoad.textContent = t("import.youtubeImportSelected");
  if (youtubeTracks.length > 1) {
    const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
    if (importYoutubeStatus) importYoutubeStatus.textContent = t("import.youtubeChooseTrack", { count: youtubeTracks.length });
    return null;
  }
  return youtubeTracks[0];
}

async function importYoutubeTrack(url: string, trackIndex: string | number): Promise<void> {
  setYoutubeImportLoading(true, "import.youtubeImporting");
  const data = await youtubeCaptionsRequest({ op: "download", url, track_index: Number(trackIndex) });
  if (!data.text) throw new Error(t("import.youtubeNoText"));
  const importText = el<HTMLTextAreaElement>("import-text");
  if (importText) importText.value = data.text;
  const importTitle = el<HTMLInputElement>("import-title");
  if (importTitle && !importTitle.value.trim()) importTitle.value = data.title || t("import.youtubeImportedTitle");
  const importAuthor = el<HTMLInputElement>("import-author");
  if (importAuthor && !importAuthor.value.trim()) importAuthor.value = data.author || "";
  setImportCoverPreview(data.thumbnailUrl || "");
  setPendingImportMeta({
    source: t("import.youtubeSource"),
    sourceUrl: data.sourceUrl || url,
    textUrl: data.sourceUrl || url
  });
  const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
  if (importYoutubeStatus) importYoutubeStatus.textContent = t("import.youtubeLoaded");
  showToast(t("toast.youtubeCaptionsLoaded"));
  // The captions are now in the books form — switch back so the user can
  // review and submit the import.
  const importModeSelect = el<HTMLSelectElement>("import-mode-select");
  if (importModeSelect) importModeSelect.value = "books";
  const importBooksMode = el<HTMLElement>("import-books-mode");
  if (importBooksMode) importBooksMode.hidden = false;
  const importYoutubeMode = el<HTMLElement>("import-youtube-mode");
  if (importYoutubeMode) importYoutubeMode.hidden = true;
}

async function handleYoutubeImport() {
  const url = el<HTMLInputElement>("import-youtube-url")?.value.trim();
  if (!url) {
    const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
    if (importYoutubeStatus) importYoutubeStatus.textContent = t("import.youtubeMissingUrl");
    return;
  }
  try {
    if (!youtubeTracks.length || youtubeTracksUrl !== url) {
      const onlyTrack = await loadYoutubeTracks(url);
      if (!onlyTrack) return;
      await importYoutubeTrack(url, onlyTrack.index);
      return;
    }
    const selectedIndex = el<HTMLSelectElement>("import-youtube-track")?.value || youtubeTracks[0]?.index;
    await importYoutubeTrack(url, selectedIndex);
  } catch (error) {
    console.warn(error);
    resetYoutubeTracks(false);
    const message = error instanceof Error && error.message.trim()
      ? safeImportErrorMessage(error)
      : t("import.youtubeError");
    const importYoutubeStatus = el<HTMLElement>("import-youtube-status");
    if (importYoutubeStatus) importYoutubeStatus.textContent = message;
    showToast(t("toast.youtubeCaptionsError"));
  } finally {
    setYoutubeImportLoading(false);
  }
}

export {
  setYoutubeImportLoading,
  resetYoutubeTracks,
  loadYoutubeTracks,
  importYoutubeTrack,
  handleYoutubeImport,
};
